baseURL = "https://www.my-blog-test.netlify.com"
languageCode = "en-us"
theme = "blog-hugo"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"




# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  pre = "edit"
  weight = 2

  [[menu.header]]
  name = "Categories"
  URL = "#categories"
  weight = 3

  [[menu.header]]
  name = "Tags"
  URL = "#tags"
  weight = 4

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 5


  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
    name = "Categories"
  URL = "#categories"
  weight = 3

  [[menu.footer]]
  name = "Tags"
  URL = "#tags"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 5


[params]

  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter","tags"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Megam"
    text2 = "solution"

  [params.footer]
      copyright = "© Raditian. All rights reserved."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"